### ISSUE TITLE
knockplop error

### ISSUE THREAD

**Issue by vasilg** [up2university/knockplop#7]
Hi, i have created a test course (v test) at the testing instance and i got the attached error
![knockplop error](https://user-images.githubusercontent.com/36266155/37200164-a6d407c0-238c-11e8-9eaf-e95cf1fb456e.png)

**Comment by michzimny** [comment]
@athird, is it only related to enabling debug info at this instance, or is it an actual error of the module?

**Comment by misi** [comment]
@alan @michzimny 
Could you give me access to login and create a course?
@vasilg 
Could you give more info how to reproduce it?

**Comment by michzimny** [comment]
@misi, please log in to https://learn.test.up2university.eu/ via any of the available identity providers, and then let me know you're in.

**Comment by vasilg** [comment]
@misi I logged in with edugain and created a new course (through Site Administration-Manage Courses and Categories - Create new course).Then i selected the v test course and the option "View".After that i was directed to the page i have sent you, without doing anything else. 

Also, we have noticed earlier that in a course that we had created yesterday (eduOER Training) the same text was displayed. 

But now, it has dissappeared in both courses :)

**Comment by misi** [comment]
I have an issue with edugain login:
![kep](https://user-images.githubusercontent.com/311629/37207616-0edd96e0-239e-11e8-9a43-f5f1f76e3747.png)

According our AAI team: 
* edupersonTargetedId is Ok. (they will fix it.)
but
* uid: A well configured IdP don't expose the uid attribute. (never ever) 
Why do you require this attribute?

@michzimny 
Until I could login with eduID, i useg google andlogged in with bakfitty@gmail.com

**Comment by michzimny** [comment]
I have granted the course creator role to your gmail user.

For the rest, see https://github.com/up2university/single-sign-on/issues/25

**Comment by misi** [comment]
I have created an access.php in theory it should fix this issue.
Unfortunately I didn't have time today to test it. 

See: 
* https://github.com/misi/knockplop-moodle/commit/71d22d57d6c7ba7f09dd6f8bb6bef87c7e56d0e4
* https://github.com/up2university/docker-moodle/pull/63

**Comment by athird** [comment]
@misi It doesn't seem to fix it. I've disabled the verbose errors on both pedagogy and test for now anyway, it seems to be a harmless error (as in, the plugin gets loaded anyway).

As a minimum, when adding/changing a capability, you need to bump the plugin version in version.php slightly in order to make Moodle add it to the database. I've done this manually and it didn't seem to help, so it's probably that there's something else going on besides that. Can you test locally when you get a chance? To see the errors, in your local instance, go to Site Administration->Development->Debugging, and set Debug messages to DEVELOPER and Display debug messages to On.

**Comment by misi** [comment]
@athird 
Sorry I was in hurry. I have left out to ++ the version.
I will try to figure out the issue and fix it today.

**Comment by misi** [comment]
@athird Could you please double-check?
I have increased version: https://github.com/misi/knockplop-moodle/commits/master
According I created a new zip and a new pull request.  https://github.com/up2university/docker-moodle/pull/64

According my tests from fresh install, it solved the original debug 'addinstance' message issue.
I could see before installing the plugin (1.0.0)  and after plugin upgrade (1.0.1) the message has disappeared.

Please let me know if you don't experience the same, and then I will continue to debug/fix it.

**Comment by misi** [comment]
Ping @athird

**Comment by misi** [comment]
Ping @athird

**Comment by misi** [comment]
Any update on this? 
If I will not get answer, then I am going to close this issue.
